<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- PARENT REFERENCE -->
    <parent>
        <groupId>io.github.dariuszciechacki</groupId>
        <artifactId>parent</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <!-- MODULE METADATA -->
    <artifactId>core</artifactId>
    <name>core</name>
    <description>Cross-cutting shared capabilities for all test modules</description>

    <!-- DEPENDENCIES -->
    <dependencies>
        <!-- Shared config support -->
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>
    </dependencies>

</project>
