name: Publish package

on:
  push:
    branches: [ build/adds-publishing-to-gh-workflow ] # change to main

jobs:
  build:
    name: Build & Deploy Maven Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GH_TOKEN
          settings-path: ${{ github.workspace }}

      - name: Build & Deploy
        run: mvn -B clean deploy -DskipTests
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Confirm deployment
        run: echo "✅ Framework successfully deployed to GitHub Packages."
